{
 "title": "Nginx Ingress Analysis",
 "description": "Nginx Ingress Error and Latency Analysis",
 "tags": [
  "nginx",
  "ingress"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Error Codes by Path",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sort_desc(sum by (status, method, path) (increase(nginx_ingress_requests_total{status=~\"[45]..\"}[$__range]))) * on(status, method, path) group_right max by (status, method, path, timestamp) (nginx_ingress_requests_total{status=~\"[45]..\"})"
    }
   ]
  },
  {
   "title": "Total Error Codes",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum by (status) (increase(nginx_ingress_requests_total{status=~\"[45]..\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Backend Response Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(nginx_ingress_backend_latency_seconds_bucket[$__rate_interval])) by (le, backend_service))",
     "legendFormat": "{{backend_service}} p95"
    }
   ]
  }
 ]
}